[package]
name = "rglua"
description = "Rust bindings to the lua api for gmod binary module creation"
version = "0.1.0"
authors = ["Vurv <vurvdevelops@gmail.com>"]
keywords = ["glua","garrysmod","lua"]
readme = "README.md"

# Remember to make your output module a cdylib.

[dependencies]
dlopen = { git = "https://github.com/Vurv78/rust-dlopen", branch = "future", features = ["derive"], version = "0.1.8" }
lazy_static = { version = "1.4.0" }